name: 'Terraform Plan/Apply'

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/env/develop/**'
    - 'terraform/modules/**'
    - '.github/workflows/deploy-develop.yml'
    - '.github/workflows/template/deploy.yml'

  pull_request:
    branches:
    - main
    paths:
    - 'terraform/env/develop/**'
    - 'terraform/modules/**'
    - '.github/workflows/deploy-develop.yml'
    - '.github/workflows/template/deploy.yml'

#These environment variables are used by the terraform azure provider to setup OIDD authenticate.
env:
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID_DEVELOP }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_DEVELOP }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY_DEVELOP }}

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: 'develop'