name: 'Store Secret Develop'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ['.github/workflows/develop-store-secret.yml']

permissions:
  id-token: write
  contents: read

jobs:
  store-secret:
    name: 'Store Secret'
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID_DEVELOP }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Download Secret
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob download --container-name backenddevelop --account-name stotfstatedevelop --name TestCsv.csv -f ./TestCsv.csv

              while IFS=, read -r col1 col2; do
                # 各行の値を変数に格納
                app_name="$col1"
                app_id="$col2"

                # ここで変数を使って処理を行う（例：表示）
                echo "App Name: $app_name"
                echo "App ID: $app_id"

              done < TestCsv.csv